worker_processes 1;

events { }

http {
    include       mime.types;  # Ważne: wczytanie typów MIME (css, js, html)
    default_type  application/octet-stream;
    client_max_body_size 500M;

    server {
        listen 80;
        server_name _;
        root /app/;
        index index.php;

        # 1. Najpierw sprawdź, czy to plik statyczny w public
        location /public/ {
            alias /app/public/;
        }

        # 2. Jeśli nie public, to przekaż wszystko do index.php (ROUTING)
        location / {
            try_files $uri $uri/ /index.php$is_args$args;
        }

        # 3. Obsługa PHP
        location ~ \.php$ {
            include fastcgi_params;
            fastcgi_pass php:9000;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            client_max_body_size 500M;
        }
    }
}